CREATE TABLE TradeHistory(
 TradeId BIGINT IDENTITY(1,1) PRIMARY KEY,
 Account NVARCHAR(50) NOT NULL,
 Asset NVARCHAR(50) NOT NULL,
 Price DECIMAL(18,4) NOT NULL,
 TradeType NVARCHAR(5) NOT NULL,
 Quantity INT NOT NULL,
 TradeTimeStamp DATETIME2 NOT NULL
		DEFAULT SYSDATETIME()
 );